# Generated by Django 5.2.7 on 2025-10-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=266)),
                ('last_name', models.CharField(max_length=266)),
                ('nickname', models.CharField(max_length=266)),
                ('rol', models.CharField(max_length=266)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
