# Generated by Django 4.2.11 on 2025-11-19 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 11, 19, 18, 4, 22, 766860, tzinfo=datetime.timezone.utc)),
        ),
    ]
