# Generated by Django 4.2.11 on 2025-11-14 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 1, 47, 2, 182498, tzinfo=datetime.timezone.utc)),
        ),
    ]
