# Generated by Django 4.2.11 on 2025-10-29 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prority', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 10, 29, 4, 20, 37, 531665, tzinfo=datetime.timezone.utc))),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='employees.employee')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='states.state')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
