# Generated by Django 4.2.11 on 2025-11-18 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 18, 21, 16, 46, 468150, tzinfo=datetime.timezone.utc))),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='roles.client')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 11, 18, 21, 16, 46, 468747, tzinfo=datetime.timezone.utc))),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_history', to='roles.employee')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_history', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'TicketHistory',
                'verbose_name_plural': 'TicketHistory',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 18, 21, 16, 46, 468464, tzinfo=datetime.timezone.utc))),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
    ]
