# Generated by Django 4.2.11 on 2025-11-14 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 1, 47, 2, 181782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 1, 47, 2, 181461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 1, 47, 2, 182063, tzinfo=datetime.timezone.utc)),
        ),
    ]
