# Generated by Django 4.2.11 on 2025-11-19 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 18, 4, 22, 761043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 18, 4, 22, 760200, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 18, 4, 22, 761711, tzinfo=datetime.timezone.utc)),
        ),
    ]
