# Generated by Django 4.2.11 on 2025-10-29 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prority',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
