# Generated by Django 4.2.11 on 2025-10-29 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='StateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateField(default=datetime.datetime(2025, 10, 29, 4, 20, 37, 531111, tzinfo=datetime.timezone.utc))),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='states.state')),
            ],
            options={
                'db_table': 'states_history',
            },
        ),
    ]
