# Generated by Django 4.2.11 on 2025-10-29 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_alter_statehistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statehistory',
            name='changed_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 4, 34, 46, 571860, tzinfo=datetime.timezone.utc)),
        ),
    ]
