# Generated by Django 4.2.11 on 2025-10-29 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_alter_statehistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statehistory',
            name='changed_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
