# Generated by Django 4.2.11 on 2025-10-29 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_alter_statehistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statehistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
