# Generated by Django 4.2.11 on 2025-10-29 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 4, 34, 46, 568517, tzinfo=datetime.timezone.utc)),
        ),
    ]
