# Generated by Django 4.2.11 on 2025-10-29 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeehistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='changed_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 4, 34, 46, 569933, tzinfo=datetime.timezone.utc)),
        ),
    ]
