# Generated by Django 4.2.11 on 2025-10-29 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_prority_ticket_priority_and_more'),
        ('employees', '0005_alter_employeehistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_history', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_history', to='tickets.ticket'),
        ),
    ]
