# Generated by Django 4.2.11 on 2025-11-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.contact')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='users.person')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
                ('id_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='users.company')),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='users.contact')),
                ('id_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='users.person')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
