# Generated by Django 4.2.11 on 2025-10-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permissions', to='roles.permission'),
        ),
        migrations.AlterField(
            model_name='rolpermission',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permissions', to='roles.rol'),
        ),
    ]
