# Generated by Django 4.2.11 on 2025-10-29 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 4, 28, 4, 956046, tzinfo=datetime.timezone.utc)),
        ),
    ]
