# Generated by Django 4.2.11 on 2025-10-29 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 10, 29, 4, 20, 37, 529618, tzinfo=datetime.timezone.utc))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employee')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
