# Generated by Django 4.2.11 on 2025-10-29 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 4, 34, 46, 570365, tzinfo=datetime.timezone.utc)),
        ),
    ]
