# Generated by Django 4.2.11 on 2025-10-29 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='employee',
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to='files/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
